theme: jekyll-theme-hacker
tittle: Welcome to the super test page
description: Feel free to bookmark this to keep an eye on my project updates
subject: This is my first time making a website. I will add as we go along. 
estended descriptions: 
